metadata:
  labels:
    app: my-pod
spec:
  containers:
  - name: xyz-app
    image: mysql
    ports:
      - name: http
        protocol: TCP
        containerPort: 80
    env:
    - name: "MYSQL_ROOT_PASSWORD"
      value: "redhat"
apiVersion: v1
kind: Pod