apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-commerce-ingress
  labels:
    app: e-commerce
spec:
  rules:
    - host: cbz.com
      http:
        paths:
        - path: /mobile
          pathType: Prefix
          backend:
            service:
              name: 
              port:
                number: 80