apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app
  labels:
    app: home-app
spec:
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: home
          image: shubhamkalsait1/home-b22:latest
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: home-app
  strategy:
    type: RollingUpdate

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloth-app
  labels:
    app: cloth-app
spec:
  template:
    metadata:
      labels:
        app: cloth-app
    spec:
      containers:
        - name: cloth
          image: shubhamkalsait1/cloth-b22:latest
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: cloth-app
  strategy:
    type: RollingUpdate