apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-app
  labels:
    app: home-app
spec:
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: home
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: xyz-app
  strategy:
    type: RollingUpdate